# Generated by Django 3.1.3 on 2022-03-22 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_Time', models.TimeField()),
                ('end_Time', models.TimeField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('subject_name', models.CharField(max_length=20)),
                ('make_available_for', models.IntegerField(default=5)),
                ('status', models.BooleanField(default=False)),
                ('student_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
