# Generated by Django 3.1.3 on 2022-03-22 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='classAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_Time', models.TimeField()),
                ('end_Time', models.TimeField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('subject_name', models.CharField(max_length=20)),
                ('make_available_for', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='studAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='attendance',
        ),
    ]
