# Generated by Django 3.1.3 on 2022-03-23 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20220323_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='classattendance',
            name='close_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='classattendance',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
