# Generated by Django 3.1.3 on 2022-03-23 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20220323_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classattendance',
            name='close_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='classattendance',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
