# Generated by Django 3.1.3 on 2022-03-26 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
